/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWorkflowStepDefinitionRequest } from './createWorkflowStepDefinitionRequest';


export interface CreateWorkflowDefinitionRequest { 
    /**
     * A description of what the step does.
     */
    description: string;
    /**
     * The event the step will raise.
     */
    triggerEventSchemaCodeName: string;
    /**
     * The steps of the workflow.
     */
    steps: Array<CreateWorkflowStepDefinitionRequest>;
}

