/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowStepInstanceResponse } from './workflowStepInstanceResponse';


export interface GetByWorkflowInstanceId200Response { 
    data?: Array<WorkflowStepInstanceResponse>;
    success?: boolean;
    error?: object;
}

