/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDataNameResponse } from './metaDataNameResponse';


export interface GetStepNames200Response { 
    data?: Array<MetaDataNameResponse>;
    success?: boolean;
    error?: object;
}

