/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowStepDefinitionResponse } from './workflowStepDefinitionResponse';


export interface GetWorkflowStepDefinitions200Response { 
    data?: Array<WorkflowStepDefinitionResponse>;
    success?: boolean;
    error?: object;
}

