/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowStepDefinitionResponse } from './workflowStepDefinitionResponse';


export interface WorkflowDefinitionResponse { 
    /**
     * Workflow definition ID
     */
    id: string;
    /**
     * Organization ID
     */
    orgId: string;
    /**
     * Organization ID
     */
    siteId: string;
    /**
     * A description of what the step does.
     */
    description: string;
    /**
     * The event that triggers this workflow.
     */
    triggerEventSchemaCodeName: WorkflowDefinitionResponse.TriggerEventSchemaCodeNameEnum;
    /**
     * The number of instances of this definition.
     */
    instanceCount?: number;
    /**
     * The number of not ready instances of this definition.
     */
    notReadyCount?: number;
    /**
     * The number of ready instances of this definition.
     */
    readyCount?: number;
    /**
     * The number of in progress instances of this definition.
     */
    inProgressCount?: number;
    /**
     * The number of successful instances of this definition.
     */
    successCount?: number;
    /**
     * The number of failed instances of this definition.
     */
    failedCount?: number;
    /**
     * The steps of the workflow.
     */
    steps: Array<WorkflowStepDefinitionResponse>;
}
export namespace WorkflowDefinitionResponse {
    export type TriggerEventSchemaCodeNameEnum = 'AuditEntryRequired' | 'MoveOutCreated' | 'ReservationCreated' | 'ReservationUpdated' | 'ReservationCancelled' | 'ReservationExpired' | 'SpaceReservationCreated' | 'LeaseCreated' | 'RentalCreated' | 'DiaryEntryRequired' | 'DiaryEntryActioned' | 'DocumentReady' | 'DocumentRequired' | 'DocumentCompleted' | 'CommunicationRequired' | 'CartLeaseItemPurchased' | 'InvoiceRequired' | 'InvoiceV2Required' | 'InvoiceStateChanged' | 'InvoiceV2LineItemRequired' | 'ImportCompleted' | 'SmartSearchCompleted' | 'PaymentRequested' | 'PaymentAttempted' | 'UpdateUnit';
    export const TriggerEventSchemaCodeNameEnum = {
        AuditEntryRequired: 'AuditEntryRequired' as TriggerEventSchemaCodeNameEnum,
        MoveOutCreated: 'MoveOutCreated' as TriggerEventSchemaCodeNameEnum,
        ReservationCreated: 'ReservationCreated' as TriggerEventSchemaCodeNameEnum,
        ReservationUpdated: 'ReservationUpdated' as TriggerEventSchemaCodeNameEnum,
        ReservationCancelled: 'ReservationCancelled' as TriggerEventSchemaCodeNameEnum,
        ReservationExpired: 'ReservationExpired' as TriggerEventSchemaCodeNameEnum,
        SpaceReservationCreated: 'SpaceReservationCreated' as TriggerEventSchemaCodeNameEnum,
        LeaseCreated: 'LeaseCreated' as TriggerEventSchemaCodeNameEnum,
        RentalCreated: 'RentalCreated' as TriggerEventSchemaCodeNameEnum,
        DiaryEntryRequired: 'DiaryEntryRequired' as TriggerEventSchemaCodeNameEnum,
        DiaryEntryActioned: 'DiaryEntryActioned' as TriggerEventSchemaCodeNameEnum,
        DocumentReady: 'DocumentReady' as TriggerEventSchemaCodeNameEnum,
        DocumentRequired: 'DocumentRequired' as TriggerEventSchemaCodeNameEnum,
        DocumentCompleted: 'DocumentCompleted' as TriggerEventSchemaCodeNameEnum,
        CommunicationRequired: 'CommunicationRequired' as TriggerEventSchemaCodeNameEnum,
        CartLeaseItemPurchased: 'CartLeaseItemPurchased' as TriggerEventSchemaCodeNameEnum,
        InvoiceRequired: 'InvoiceRequired' as TriggerEventSchemaCodeNameEnum,
        InvoiceV2Required: 'InvoiceV2Required' as TriggerEventSchemaCodeNameEnum,
        InvoiceStateChanged: 'InvoiceStateChanged' as TriggerEventSchemaCodeNameEnum,
        InvoiceV2LineItemRequired: 'InvoiceV2LineItemRequired' as TriggerEventSchemaCodeNameEnum,
        ImportCompleted: 'ImportCompleted' as TriggerEventSchemaCodeNameEnum,
        SmartSearchCompleted: 'SmartSearchCompleted' as TriggerEventSchemaCodeNameEnum,
        PaymentRequested: 'PaymentRequested' as TriggerEventSchemaCodeNameEnum,
        PaymentAttempted: 'PaymentAttempted' as TriggerEventSchemaCodeNameEnum,
        UpdateUnit: 'UpdateUnit' as TriggerEventSchemaCodeNameEnum
    };
}


