/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkflowStepDefinitionResponse { 
    /**
     * Workflow Step Definition ID
     */
    id: string;
    /**
     * Workflow Definition ID of this step
     */
    workflowDefinitionId: string;
    /**
     * The type of this step
     */
    stepTypeId: WorkflowStepDefinitionResponse.StepTypeIdEnum;
    /**
     * A description of what the step does.
     */
    description: string;
    /**
     * The event that will trigger this step.
     */
    executionTriggerValue?: string;
    /**
     * The number of minutes after finishing the previous step that this step should execute by.
     */
    delay?: number;
    /**
     * The event the step will raise.
     */
    raiseEventSchemaCodeName?: string;
    /**
     * Step position
     */
    stepPosition: number;
    /**
     * Previous step position
     */
    previousStep?: number;
    /**
     * Next step position
     */
    nextStep?: number;
    /**
     * The number of times this step can run.
     */
    maxCount: number;
    /**
     * Mappings
     */
    mappings: object;
    /**
     * Literals
     */
    literals: object;
    /**
     * Templates
     */
    templates: object;
}
export namespace WorkflowStepDefinitionResponse {
    export type StepTypeIdEnum = 1 | 2 | 3;
    export const StepTypeIdEnum = {
        NUMBER_1: 1 as StepTypeIdEnum,
        NUMBER_2: 2 as StepTypeIdEnum,
        NUMBER_3: 3 as StepTypeIdEnum
    };
}


