/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowStepDefinitionResponse } from './workflowStepDefinitionResponse';


export interface WorkflowDefinitionResponse { 
    /**
     * Workflow definition ID
     */
    id: string;
    /**
     * Organization ID
     */
    orgId: string;
    /**
     * Organization ID
     */
    siteId: string;
    /**
     * A description of what the step does.
     */
    description: string;
    /**
     * The event the step will raise.
     */
    triggerEventSchemaCodeName: string;
    /**
     * The number of instances of this definition.
     */
    instanceCount?: number;
    /**
     * The number of not ready instances of this definition.
     */
    notReadyCount?: number;
    /**
     * The number of ready instances of this definition.
     */
    readyCount?: number;
    /**
     * The number of in progress instances of this definition.
     */
    inProgressCount?: number;
    /**
     * The number of successful instances of this definition.
     */
    successCount?: number;
    /**
     * The number of failed instances of this definition.
     */
    failedCount?: number;
    /**
     * The steps of the workflow.
     */
    steps: Array<WorkflowStepDefinitionResponse>;
}

